require('dotenv').config();
const { GoogleGenerativeAI } = require("@google/generative-ai");
const axios = require('axios');
const FormData = require('form-data');

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
const telegramToken = process.env.TELEGRAM_BOT_TOKEN;
const telegramChatId = process.env.TELEGRAM_CHAT_ID;

async function runBot() {
    console.log("💎 Luxury Snap Engine Started...");

    try {
        const model = genAI.getGenerativeModel({ model: "gemini-flash-latest" });

        // 🔥 LUXURY CONTENT ENGINE
        const scenes = [
            'luxury hotel lobby at night',
            'high-end penthouse interior with skyline view',
            'rainy neon luxury city street',
            'minimalist luxury bedroom morning light',
            'rooftop infinity pool overlooking city',
            'luxury shopping mall with reflections',
            'wide cinematic bridge road at sunset',
            'underground luxury parking with supercars'
        ];

        const moods = [
            'quiet late night energy',
            'soft peaceful morning',
            'slightly lonely but calm',
            'private luxury moment',
            'dreamy cinematic silence'
        ];

        const lightingStyles = [
            'warm golden hour light',
            'soft diffused ambient lighting',
            'neon reflections on wet ground',
            'cool cinematic blue tones',
            'sunset glow with shadows'
        ];

        const cameraStyles = [
            'shot on 35mm lens',
            'ultra wide cinematic framing',
            'low angle perspective',
            'depth of field focus',
            'soft background blur'
        ];

        const randomScene = scenes[Math.floor(Math.random() * scenes.length)];
        const randomMood = moods[Math.floor(Math.random() * moods.length)];
        const randomLight = lightingStyles[Math.floor(Math.random() * lightingStyles.length)];
        const randomCamera = cameraStyles[Math.floor(Math.random() * cameraStyles.length)];

        // 🧠 ADVANCED PROMPT (ANTI-AI LOOK)
        const promptInstruction = `
Act as a top-tier cinematic photographer and luxury visual director.

Create a HIGH-END, ultra realistic image generation prompt.

GOAL:
Make the image look like a real photo taken in a luxury environment, not AI generated.

SCENE:
${randomScene}

MOOD:
${randomMood}

LIGHTING:
${randomLight}

CAMERA:
${randomCamera}

STRICT RULES:
- Ultra realistic photography (NOT 3D render style)
- Use real-world imperfections (slight blur, grain, reflections)
- Natural lighting behavior
- Clean composition, minimal clutter
- Materials must feel real: marble, glass, polished metal
- Include depth and atmosphere
- Avoid futuristic sci-fi overload

KEYWORDS TO INCLUDE:
photorealistic, cinematic lighting, 8k, realistic textures, natural shadows, subtle reflections, depth of field

OUTPUT:
Return ONLY the final prompt in English.
`;

        // 🔁 Generate Prompt
        let promptGenere = null;
        for (let i = 0; i < 5; i++) {
            try {
                const result = await model.generateContent(promptInstruction);
                promptGenere = result.response.text().trim();
                console.log("✅ Prompt generated");
                break;
            } catch {
                await new Promise(r => setTimeout(r, 4000));
            }
        }

        if (!promptGenere) throw new Error("Prompt generation failed");

        // 🎨 Generate Image
        let buffer = null;

        for (let i = 0; i < 5; i++) {
            try {
                const response = await axios.post(
                    "https://router.huggingface.co/hf-inference/models/black-forest-labs/FLUX.1-schnell",
                    { inputs: promptGenere },
                    {
                        headers: {
                            Authorization: `Bearer ${process.env.HF_TOKEN}`,
                            "Content-Type": "application/json",
                            Accept: "image/png"
                        },
                        responseType: "arraybuffer",
                        timeout: 90000
                    }
                );

                buffer = Buffer.from(response.data, "binary");
                console.log("✅ Image generated");
                break;

            } catch {
                await new Promise(r => setTimeout(r, 5000));
            }
        }

        const telegramUrl = `https://api.telegram.org/bot${telegramToken}`;

        // 🧠 HUMAN SNAP CAPTIONS (Generated by Gemini)
        const captionInstruction = `
Act like a real Snapchat user.

Write a SHORT caption (max 6 words).
Style:
- lowercase only
- no punctuation except emojis
- emotional, natural, human
- not motivational quotes
- not AI sounding
- feels like texting a friend

Examples:
"this feels different 🖤"
"late nights like this"
"one day fr"
"i need this life"
"peace like this hits"

Only output the caption.
`;

        let caption = "this feels different 🖤";

        try {
            const result = await model.generateContent(captionInstruction);
            caption = result.response.text().trim();
        } catch { }

        const safePrompt = promptGenere.length > 800
            ? promptGenere.substring(0, 800) + "..."
            : promptGenere;

        if (buffer) {
            // 📸 SEND IMAGE (CLEAN)
            const form = new FormData();
            form.append('chat_id', telegramChatId);
            form.append('caption', caption);
            form.append('photo', buffer, { filename: 'luxury.png' });

            await axios.post(`${telegramUrl}/sendPhoto`, form, {
                headers: form.getHeaders()
            });

            console.log("🚀 Image sent");

            // 🧠 SEND PROMPT (SEPARATE MESSAGE)
            await axios.post(`${telegramUrl}/sendMessage`, {
                chat_id: telegramChatId,
                text: `🧠 Prompt:\n\`${safePrompt}\``,
                parse_mode: 'Markdown'
            });

            console.log("🧠 Prompt sent");

        } else {
            await axios.post(`${telegramUrl}/sendMessage`, {
                chat_id: telegramChatId,
                text: `⚠️ Image failed\n\n${safePrompt}`
            });
        }

    } catch (err) {
        console.error("❌ Error:", err.message);
    }
}

runBot();